### ISSUE TITLE
Mode switching problems

### ISSUE THREAD

**Issue by k3rni** [k3rni/foggy#2]
Reported by @vonpupp in #1 

Steps to reproduce:
1. Use <kbd>mod-p</kbd>, go to mode (my current mode is `1366x768@60`).
2. Change the mode to `1024x768@60`. This works fine. Now repeat it again to go back to the prior mode
3. Use <kbd>mod-p</kbd> again and go to mode, and select `1024x768@60` and an error pops up:

Herewith the full trace:

```
W: awesome: luaA_dofunction:78: error while running function
stack traceback:
    [C]: in function 'string.format'
    /home/av/.config/awesome/foggy/xrandr.lua:160: in field 'set_mode'
    /home/av/.config/awesome/foggy/menu.lua:80: in local 'cmd'
    /usr/share/awesome/lib/awful/menu.lua:260: in function 'awful.menu.exec'
    /usr/share/awesome/lib/awful/menu.lua:403: in upvalue 'press'
    /usr/share/awesome/lib/awful/button.lua:42: in function </usr/share/awesome/lib/awful/button.lua:42>
    [C]: in method 'emit_signal'
    /usr/share/awesome/lib/wibox/widget/base.lua:59: in function 'wibox.widget.base.handle_button'
    (...tail calls...)
    /usr/share/awesome/lib/gears/object.lua:68: in function 'gears.object.emit_signal'
    /usr/share/awesome/lib/wibox/drawable.lua:279: in function </usr/share/awesome/lib/wibox/drawable.lua:273>
error: /home/av/.config/awesome/foggy/xrandr.lua:160: bad argument #5 to 'format' (number has no integer representation)
```

Note that if I go to mode - auto it works fine. Perhaps it is a similar issue with argument casting.

**Comment by k3rni** [comment]
It is strange that it only happens some of the time.

However, the tracebacks points (as noted) to the fact that Lua 5.1 accepts floats as input to `string.format("%d")`, while Lua 5.3 doesn't.

XRandR can report modes with non-integer refresh rates, that's fine. But then foggy fails when formatting them as integers to pass to mode setting.

**Comment by k3rni** [comment]
@vonpupp please check the latest version. We'll investigate further if it doesn't fix your issue.

**Comment by vonpupp** [comment]
Hello @k3rni, I tried it and everything seems to work fine. Thank you very much!

I cannot close the issue, I believe it is because you opened it.
